version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    restart: always
    expose:
      - "8000"
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      # Kafka Configuration
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_SASL_USERNAME=${KAFKA_SASL_USERNAME}
      - KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - KAFKA_SASL_MECHANISM=PLAIN
      - KAFKA_TOPIC=weathertopic

  frontend:
    build: 
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    restart: always
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL_SERVER=http://backend:8000
    depends_on:
      - backend